name: Create GitHub Release and Publish to TER

on:
  push:
    tags:
      - '*'

env:
  TYPO3_EXTENSION_KEY: prometheus
  EXTENSION_ARTEFACT: prometheus_${{ github.ref_name }}.zip

jobs:
  build:
    name: Build extension artefact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check tag
        run: |
          if ! [[ ${{ github.ref_name }} =~ ^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2, typo3/tailor, clue/phar-composer
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@4.0.0

      - name: Build vendor phar
        run: |
          composer install -d Resources/Private/Libs/Build
          phar-composer build Resources/Private/Libs/Build Resources/Private/Libs/vendors.phar

      - name: Create artefact
        run: |
          echo "Mfd\Prometheus\Extension::loadVendorLibraries();" >> ext_localconf.php
          php ~/.composer/vendor/bin/tailor set-version "${{ github.ref_name }}"
          php ~/.composer/vendor/bin/tailor create-artefact "${{ github.ref_name }}"

      - name: Upload extension artefact
        uses: actions/upload-artifact@v4
        with:
          name: extension-artefact
          path: tailor-version-artefact/${{ env.EXTENSION_ARTEFACT }}

  release:
    name: Create release
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      release-notes-url: ${{ steps.create-release.outputs.url }}
    steps:
      - uses: actions/checkout@v4

      - name: Download extension artefact
        id: download
        uses: actions/download-artifact@v4
        with:
          name: extension-artefact

      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          files: ${{ steps.download.outputs.download-path }}/${{ env.EXTENSION_ARTEFACT }}

  ter-publish:
    name: Publish on TER
    needs: [release]
    runs-on: ubuntu-latest
    env:
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Download extension artefact
        id: download
        uses: actions/download-artifact@v4
        with:
          name: extension-artefact

      - name: Get tag message
        id: tag-message
        run: |
          {
            echo 'body<<EOF'
            git tag -l --format='%(contents)' '${{ github.ref_name }}'
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: intl, mbstring, json, zip, curl
          tools: composer:v2, typo3/tailor

      - name: Publish to TER
        run: |
          php ~/.composer/vendor/bin/tailor ter:publish \
            --comment "${{ steps.tag-message.outputs.body }}" \
            --artefact "${{ steps.download.outputs.download-path }}/${{ env.EXTENSION_ARTEFACT }}" \
            "${{ github.ref_name }}"
